### ISSUE TITLE
espnow on arduino?

### ISSUE THREAD

**Issue by ShreddinPB** [dpoulson/bb8_rc_control#1]
This isnt really an issue with your code, I just cant figure out how to get espnow.h installed for arduino. I have looked all over and the official page takes me to wifiespnow.h library. How do I go about getting the standard one installed on arduino? I have both the esp8266 and esp32 board managers added, just cant find out how to add espnow.
Thank you, looking forward to using this as I wasnt to make a remote out of an esp32 also and have all 3 on espnow ;)

**Comment by dpoulson** [comment]
esp_now.h is included in the ESP boards. I'm running 2.0.5 of ESP32.

./.arduino15/packages/esp32/hardware/esp32/2.0.5/tools/sdk/esp32/include/esp_wifi/include/esp_now.h

I know I've followed old instructions in the past which had a different link to the board manager json file which was out of date. 

This is the one I use.

https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json

**Comment by ShreddinPB** [comment]
Thanks for your fast reply! I appreciate you putting up this code. I was looking at the normal bb-8 builders stuff and couldnt imagine using all those separate little micros for just the body.
So, the problem was user error, I was trying to compile for an ESP32 for the dome since I have a tinyS3 sitting here which has battery charging built in so I wanted to use it for the dome with a little lipo. I changed ESP8266Wifi.h to just Wifi.h but then it couldnt find espnow.h, which looks like for an ESP32 you use esp_now.h ?
Also there was 3 more dependencies I had to add, not sure if I got the right ones as drive.ino is having issues compiling.
These 3 were the ones I guessed on, ESP32Servo, Arduino-PID-Library, and SPort.

**Comment by dpoulson** [comment]
Glad you got it sorted. I'm currently trying to get my printers working so I can finish the main sphere and actually test the drive system out. Then I'll be able to document it more! :P And also once I've confirmed the design of the PCB then I'll be offering kits (at cost, no profit!) from my website. 

So the dependencies I use are: 

Adafruit BNO055 - 1.6.0
Adafruit Neopixel - 1.10.6
BTS7960 - 1.0.0
DFRobotDFPlayerMini - 1.0.5
ESP32Servo - 0.11.0
PID - 1.2.0
S.Port sensor library for FrSky - 1.0.3

I think thats it. :)

**Comment by ShreddinPB** [comment]
Well, I got the dome compiling. I am getting a butt ton of errors compiling
the drive. I did also have to add ESPSoftwareSerial since SBus seems to
need it and ESP32 doesnt support it.
I am getting a lot of "'CH_SOUND_VOLUME' was not declared in this scope"
and other things, I assume those just need to be defined in constants.h?
After that I get these "'class bfs::SbusRx' has no member named 'ch'" but
im thinking maybe if I get the defines in there that might go away as I did
look in the sbus docs and .ch is there lol

**Comment by dpoulson** [comment]
Ah yeah, the problem with something being actively developed. I add things, but forget to sort the documentation or default files. :D

I've just pushed a new version with an updated constant.h-default. Bunch of new values added. Not sure about the sbus errors. Have you got the right library installed? (The Bolder Flight Systems one?)

See how it goes with all the extra values in constants.h

Darren.

**Comment by ShreddinPB** [comment]
Youre awesome, thanks for doin that so fast!
Yeah I double checked it, after I get the new constants in i'll debug more.
And I totally get it, active development and alpha like so things happen,
just glad you shared it!

**Comment by ShreddinPB** [comment]
I joined the discord you linked in the readme, whats your name on there? Im
still getting those errors and we dont need to hash it out here hahaha

**Comment by dpoulson** [comment]
Latest version of SBus library seems to have breaking changes. Until I have time to fix this, use version 7.0.0
